# This "input" configures a global authorization rule to enable public access to
# all models in this schema. Learn more about authorization rules here: https://docs.amplify.aws/cli/graphql/authorization-rules
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @hasMany
}

type Post @model {
  id: ID!
  title: String!
  blog: Blog @belongsTo
  comments: [Comment] @hasMany
}

type Comment @model {
  id: ID!
  post: Post @belongsTo
  content: String!
  testAttribute: String!
}

type BlogTest @model {
  id: ID!
  name: String!
  posts: [PostTest] @hasMany
}

type PostTest @model {
  id: ID!
  title: String!
  blog: BlogTest @belongsTo
  comments: [CommentTest] @hasMany
}

type CommentTest @model {
  id: ID!
  post: PostTest @belongsTo
  content: String!
  testAttribute: String!
  testAttribute2: String!
}

type BlogTest2 @model {
  id: ID!
  name: String!
  posts: [PostTest2] @hasMany
}

type PostTest2 @model {
  id: ID!
  title: String!
  blog: BlogTest2 @belongsTo
  comments: [CommentTest2] @hasMany
}

type CommentTest2 @model {
  id: ID!
  post: PostTest2 @belongsTo
  content: String!
}